### ISSUE TITLE
Malloc deadlock in rendering large OBJ

### ISSUE THREAD

**Issue by tdewolff** [fogleman/ln#7]
Running

```
package main

import "github.com/fogleman/ln/ln"

func main() {
    tree, err := ln.LoadOBJ("tree.obj")
    if err != nil {
        panic(err)
    }

    scene := ln.Scene{}
    scene.Add(tree)

    // define camera parameters
    eye := ln.Vector{4, 3, 2}    // camera position
    center := ln.Vector{0, 0, 0} // camera looks at
    up := ln.Vector{0, 0, 1}     // up direction

    // define rendering parameters
    width := 1024.0  // rendered width
    height := 1024.0 // rendered height
    fovy := 50.0     // vertical field of view, degrees
    znear := 0.1     // near z plane
    zfar := 10.0     // far z plane
    step := 0.01     // how finely to chop the paths for visibility testing

    // compute 2D paths that depict the 3D scene
    paths := scene.Render(eye, center, up, width, height, fovy, znear, zfar, step)

    paths.WriteToPNG("out.png", width, height)

    // save the paths as an svg
    paths.WriteToSVG("out.svg", width, height)
}
```

with `tree.obj` being a large OBJ file (15MB) gives

```
panic: fatal error: malloc deadlock

runtime stack:
runtime.throw(0x151fc0, 0xf)
        /home/pi/golang/go/src/runtime/panic.go:527 +0x78
runtime.mallocgc(0x21, 0x0, 0x3, 0x1864a8)
        /home/pi/golang/go/src/runtime/malloc.go:513 +0x13c
runtime.rawstring(0x21, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/golang/go/src/runtime/string.go:264 +0x64
runtime.rawstringtmp(0x0, 0x21, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/pi/golang/go/src/runtime/string.go:107 +0xb4
runtime.concatstrings(0x0, 0x45f57a38, 0x2, 0x2, 0x0, 0x0)
        /home/pi/golang/go/src/runtime/string.go:48 +0x1e4
runtime.concatstring2(0x0, 0x1523c0, 0xf, 0x1556e8, 0x12, 0x0, 0x0)
        /home/pi/golang/go/src/runtime/string.go:58 +0x58
runtime.(*errorString).Error(0x569a4010, 0x0, 0x0)
        <autogenerated>:2 +0xd8
runtime.printany(0x12b5b0, 0x569a4010)
        /home/pi/golang/go/src/runtime/error.go:75 +0x140
runtime.gopanic(0x12b5b0, 0x569a4010)
        /home/pi/golang/go/src/runtime/panic.go:352 +0x5c
runtime.panicindex()
        /home/pi/golang/go/src/runtime/panic.go:12 +0x48
runtime.mHeap_Grow(0x1ed0e0, 0x8, 0x0)
        /home/pi/golang/go/src/runtime/mheap.go:647 +0x25c
runtime.mHeap_AllocSpanLocked(0x1ed0e0, 0x1, 0x0)
        /home/pi/golang/go/src/runtime/mheap.go:532 +0x6c8
runtime.mHeap_Alloc_m(0x1ed0e0, 0x1, 0xd, 0x0, 0x5d26c)
        /home/pi/golang/go/src/runtime/mheap.go:425 +0x23c
runtime.mHeap_Alloc.func1()
        /home/pi/golang/go/src/runtime/mheap.go:484 +0x40
runtime.systemstack(0x45f57be4)
        /home/pi/golang/go/src/runtime/asm_arm.s:256 +0xa8
runtime.mHeap_Alloc(0x1ed0e0, 0x1, 0xd, 0x100, 0x1)
        /home/pi/golang/go/src/runtime/mheap.go:485 +0x58
runtime.mCentral_Grow(0x1f20d0, 0x0)
        /home/pi/golang/go/src/runtime/mcentral.go:190 +0xb0
runtime.mCentral_CacheSpan(0x1f20d0, 0x43ada1ac)
        /home/pi/golang/go/src/runtime/mcentral.go:86 +0x5e0
runtime.mCache_Refill(0x4685925c, 0xd, 0x43ada1ac)
        /home/pi/golang/go/src/runtime/mcache.go:118 +0xd4
runtime.mallocgc.func2()
        /home/pi/golang/go/src/runtime/malloc.go:611 +0x28
runtime.systemstack(0x569b7400)
        /home/pi/golang/go/src/runtime/asm_arm.s:242 +0x80
runtime.mstart()
        /home/pi/golang/go/src/runtime/proc1.go:674

goroutine 1 [running]:
runtime.systemstack_switch()
        /home/pi/golang/go/src/runtime/asm_arm.s:187 +0x4 fp=0x5ec8b90c sp=0x5ec8b908
runtime.mallocgc(0xc0, 0x0, 0x3, 0x8)
        /home/pi/golang/go/src/runtime/malloc.go:612 +0x840 fp=0x5ec8b978 sp=0x5ec8b90c
runtime.rawmem(0xc0, 0x30)
        /home/pi/golang/go/src/runtime/malloc.go:788 +0x30 fp=0x5ec8b98c sp=0x5ec8b978
runtime.growslice(0x136148, 0x768e44e0, 0x4, 0x4, 0x5, 0x0, 0x0, 0x0)
        /home/pi/golang/go/src/runtime/slice.go:92 +0x230 fp=0x5ec8b9c4 sp=0x5ec8b98c
github.com/fogleman/ln/ln.Path.Chop(0x59a9e840, 0x2, 0x2, 0x47ae147b, 0x3f847ae1, 0x0, 0x0, 0x0)
        /home/pi/golang/projects/src/github.com/fogleman/ln/ln/path.go:41 +0x434 fp=0x5ec8bb28 sp=0x5ec8b9c4
github.com/fogleman/ln/ln.Paths.Chop(0x61e14000, 0xe29c8, 0xe2aaa, 0x47ae147b, 0x3f847ae1, 0x0, 0x0, 0x0)
        /home/pi/golang/projects/src/github.com/fogleman/ln/ln/path.go:131 +0xc0 fp=0x5ec8bb88 sp=0x5ec8bb28
github.com/fogleman/ln/ln.(*Scene).Render(0x576ac340, 0x0, 0x40100000, 0x0, 0x40080000, 0x0, 0x40000000, 0x0, 0x0, 0x0, ...)
        /home/pi/golang/projects/src/github.com/fogleman/ln/ln/scene.go:47 +0x398 fp=0x5ec8be7c sp=0x5ec8bb88
main.main()
        /home/pi/golang/projects/src/github.com/tdewolff/tree/main.go:28 +0x2e0 fp=0x5ec8bf9c sp=0x5ec8be7c
runtime.main()
        /home/pi/golang/go/src/runtime/proc.go:111 +0x2b4 fp=0x5ec8bfc4 sp=0x5ec8bf9c
runtime.goexit()
        /home/pi/golang/go/src/runtime/asm_arm.s:1036 +0x4 fp=0x5ec8bfc4 sp=0x5ec8bfc4

goroutine 17 [syscall, 2 minutes, locked to thread]:
runtime.goexit()
        /home/pi/golang/go/src/runtime/asm_arm.s:1036 +0x4
```

on a Raspberry Pi 2B, Debian. The OBJ file I used is here: http://pi.tacodewolff.nl:8080/tree.obj

**Comment by fogleman** [comment]
Sounds like you don't have enough RAM. Not much I can do about that...
